### ISSUE TITLE
Reporte de entrevista

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-2-entrevista-awua-de-limon#2]
[Reporte de entrevista.pdf](https://github.com/user-attachments/files/16859956/Reporte.de.entrevista.pdf)

**Comment by Nelsy21** [comment]
Preparación: El equipo preparó lo necesario para la entrevista documentando cada fase del proceso necesario  5
Conocimiento Ganado: Se cumple el objetivo planteado inicialmente 5
Estructura del informe: Presenta los criterios necesarios para un reporte, (Objetivos, materiales, Introducción, desarrollo, etc...) 5
Redacción: Pioriza las ideas generales y se redactan adecuadamente para la comprensión 5
total: 20
Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
